CREATE DATABASE KSR_DB;
USE KSR_DB;
#SELECT DATABASE()  # CHECK WHICH DATABASE IS ACTIVE
SHOW TABLES;
CREATE TABLE CUSTOMER_TB (
CUST_NAME CHAR(20),
CUST_AGE INT,
CUST_LOCATION CHAR(30),
CUST_PHNO INT);

#DROP TABLE CUSTOMER_TB;

#TO INSERT DATA
INSERT INTO CUSTOMER_TB VALUES ("KAMAL",26,"BANGLORE",13243566);
INSERT INTO CUSTOMER_TB VALUES ("RUMI",NULL,"BANGLORE",13243566);
INSERT INTO CUSTOMER_TB VALUES ("BUBBY",25,"TORONTO",1334762897);
INSERT INTO CUSTOMER_TB VALUES ("RUMI",NULL,"BANGLORE",13243566);
INSERT INTO CUSTOMER_TB (CUST_NAME, CUST_LOCATION, CUST_PHNO) VALUES ("RUMI","BANGLORE",13243566);
INSERT INTO CUSTOMER_TB VALUES ("KK",26,NULL,NULL);

SELECT * FROM CUSTOMER_TB;

#UPDATE LOCATION

#SET SQL_SAFE_UPDATES = 0; # UPDATION DON'T WORK IF SAFE UPDATE MODE=1
UPDATE CUSTOMER_TB SET CUST_LOCATION="DELHI" WHERE CUST_NAME ="KAMAL";
UPDATE CUSTOMER_TB SET CUST_LOCATION="GOA",CUST_AGE=27 WHERE CUST_NAME ="KAMAL";
SELECT * FROM CUSTOMER_TB;


#DELETE EXISTING RECORD
DELETE FROM CUSTOMER_TB WHERE CUST_NAME="KK";

#GRANT ACCESS FOR THE TABLE
create user 'user1' identified by 'ChangeMe' password expire;
GRANT SELECT ON CUSTOMER_TB TO 'user1';
GRANT update ON CUSTOMER_TB TO 'user1';
GRANT SELECT(CUST_NAME,CUST_AGE,CUST_LOCATION) ON CUSTOMER_DB TO 'user1';
REVOKE SELECT ON CUSTOMER_TB FROM 'user1';


#change TABLE STRUCTURE

ALTER TABLE CUSTOMER_TB ADD COLUMN CUST_EMAIL CHAR(40);

ALTER TABLE CUSTOMER_TB DROP COLUMN CUST_PHNO;
ALTER TABLE CUSTOMER_TB ADD COLUMN CUST_EMAIL CHAR(40) AFTER CUST_AGE;

SELECT CURRENT_ROLE();



