SET SQL_SAFE_UPDATES = 0;
use ksr_db;

create table phone_numbers(
name char(20),
phno bigint
);

INSERT INTO PHONE_NUMBERS VALUES( "KAMAL", 999999999);
INSERT INTO PHONE_NUMBERS VALUES("BUBBY",9082347875);

#TINYINT ---- 127 CAN BE GIVEN TO AGE
#SMALLINT
#INT
#BIGINT
#MEDIUMINT

USE KSR_DB;
CREATE TABLE CUSTOMER_INFO(
ID INT,
FIRST_NAME VARCHAR(20),
LAST_NAME VARCHAR(20),
AGE TINYINT,
ADDRESS VARCHAR(200),
LOCATION VARCHAR(20),
PHONE_NUMBER BIGINT
);

INSERT INTO CUSTOMER_INFO VALUES (1,'BALA','J',28 ,'#32 WHITEFIELD,BANGALORE', 'INDIA',7937439757);
INSERT INTO CUSTOMER_INFO VALUES (1,'BALA','BALA',28 ,'#32 WHITEFIELD,BANGALORE', 'INDIA',90359);
INSERT INTO CUSTOMER_INFO VALUES (1,'','J',28 ,'#32 WHITEFIELD,BANGALORE', 'INDIA',90359);

select * FROM CUSTOMER_INFO;
#UPDATE CUSTOMER_INFO SET AGE=-12 WHERE LAST_NAME='BALA';
#UPDATE CUSTOMER_INFO SET AGE=5 WHERE FIRST_NAME='';

#CONSTRAINTS
#PRIMARY KEY ---- NOT NULL, UNIQUE
#FOREIGN KEY ---REFERED FROM PRIMARY KEY, CAN CONTAIN NULL, DUPLICATES
#UNIQUE --- CAN BE NULL BUT NO DUPLICATES
#NOT NULL ----CAN NOT BE NULL, DUPLICATES CAN BE
#CHECK ---- CHECK CONDITION
#DEFAULT ----SET A DEFAULT VALUE WHEN NO VALUE IS SPECIFIED