USE KSR_DB;

CREATE TABLE CUST_INFO(
ID INT PRIMARY KEY,
FIRST_NAME VARCHAR(20) NOT NULL,
LAST_NAME VARCHAR(20) NOT NULL,
AGE INT CHECK(AGE>18),
ADDRESS VARCHAR(200) UNIQUE,
LOCATION VARCHAR(10) DEFAULT 'INDIA',
PHONE_NUMBER BIGINT CHECK(LENGTH(PHONE_NUMBER)=10),
UNIQUE(PHONE_NUMBER),
CHECK(FIRST_NAME!=LAST_NAME)
);

INSERT INTO CUST_INFO VALUES (1,'KAMALJEET', 'KAUR',26,'BARAM','US',9991307072),
(2,'SARAVJEET', 'SINGH',55,'TORONTO','US',7082701706),
(3,'PARAM', 'SANDHU',20,'CHAHARWALA','CANADA',7015111044),
(4,'PARMINDER', 'SANDHU',30,'HARIPUR','GERMANY',8814933857),
(5,'CHARANJEET', 'SINGH',55,'CALGIRI','US',8930154030);

SELECT * FROM CUST_INFO;

CREATE TABLE SALES_INFO(
C_ID INT,
PRODUCT_NAME VARCHAR(20),
SALES INT,
FOREIGN KEY (C_ID) REFERENCES CUST_INFO(ID)
);

INSERT INTO SALES_INFO VALUES (1, 'IPHONE',86000),
(1,'WATCH',3500),
(1,'POWERBANK',5000),
(2,'PEN',100),
(NULL, 'CLOCK', 600)
;

#FOREING KEY COLUMN OF SALES_INFO CAN CONTAIN NULL BUT NOT AN ID WHICH IS NOT PRESENT IN CUST_INFO TABLE
#FOREIGN KEY CONSTRAINT WILL BE VIOLATED