DROP table IF EXISTS STUDENT_MARKS_ALL ;
CREATE TABLE STUDENT_MARKS_ALL (
S_NAME VARCHAR(30), 
S_SUBJECT VARCHAR(30), 
MARKS INT);
SELECT * FROM STUDENT_MARKS_ALL;
INSERT INTO STUDENT_MARKS_ALL VALUES
('KAMAL', 'MATHS', 99),
('KAMAL', 'SCIENCE', 85),
('KAMAL', 'COMPUTER', 94),
('SARAB', 'MATHS', 98),
('SARAB', 'SCIENCE', 84),
('SARAB', 'COMPUTER', 99),
('PARAM', 'MATHS', 98),
('PARAM', 'SCIENCE', 98),
('PARAM', 'COMPUTER' ,98)
;

SELECT * FROM STUDENT_MARKS_ALL;
SELECT * FROM (
SELECT S_NAME, TOTAL_MARKS, RANK() OVER (ORDER BY TOTAL_MARKS) AS RNK FROM (SELECT S_NAME, SUM(MARKS) AS TOTAL_MARKS
FROM STUDENT_MARKS_ALL
GROUP BY S_NAME) A) B
WHERE RNK=2;

WITH CTE1 AS (SELECT S_NAME, SUM(MARKS) AS TOTAL_MARKS FROM STUDENT_MARKS_ALL GROUP BY S_NAME),
CTE2 AS (SELECT *, RANK() OVER(ORDER BY TOTAL_MARKS DESC) AS RNK FROM CTE1)
SELECT * FROM CTE2 WHERE RNK=2;

select * from WINDOWS_FUNc1;
with cte as (select s_year,s_product, t_sales, lag(t_sales) over(partition by s_product order by s_year) as yoy_sales from windows_func1),
cte1 as (select s_year,s_product,t_sales,yoy_sales,((t_sales-yoy_sales)/yoy_sales)*100 as percent_inc_dec from cte)
select * from cte1;

SELECT * FROM EMPLOYEE_TB;
SELECT * FROM 
(SELECT ID,NAME,DEPARTMENT_ID,SALARY, RANK() OVER(PARTITION BY DEPARTMENT_ID ORDER BY SALARY DESC) AS RNK FROM EMPLOYEE_TB) A
WHERE RNK=2;

WITH CTE AS (SELECT ID,NAME,DEPARTMENT_ID,SALARY, RANK() OVER(PARTITION BY DEPARTMENT_ID ORDER BY DEPARTMENT_ID, SALARY DESC) AS RNK FROM EMPLOYEE_TB)
SELECT * FROM CTE WHERE RNK;
